### ISSUE TITLE
RRLyrae website down

### ISSUE THREAD

**Issue by ebachelet** [astroML/gatspy#35]
Hello  

It seems this website is now down : 

http://www.mpia.de/~bsesar/S82_RRLyr/RRLyr_ugriz_templates.tar.gz

creating crash when requested. The template seems to be here : 

http://www.astro.caltech.edu/~bsesar/S82_RRLyr/RRLyr_ugriz_templates.tar.gz

or in SIMBAD. 

Is it possible to have an update?

Thanks

**Comment by bsipocz** [comment]
It's also available in `astroML-data`, the new central place where we plan to store these datasets:
https://github.com/astroML/astroML-data/tree/master/datasets

**Comment by ebachelet** [comment]
Great! Does that mean gatspy will implement this dataset from AstroML soon?

**Comment by mtlam** [comment]
Are the other data sets planned to be stored there? For example, just trying `fetch_rrlyrae()`, table1.tar.gz doesn't exist so this command won't run. Thanks.

**Comment by bsipocz** [comment]
@mtlam - which function rrlyrae function do you try to use, could you provide a full example you're running? I'll try to reproduce, but I don't think there is a `fetch_rrlyrae()`, neither can I find the trace of a `table1.tar.gz` file.

**Comment by ankanaan** [comment]
Hi guys,

I recently installed gatpy + astroML.  Trying to test it I found the same error as ebachelet.  I tried changing the url in the call to fetch_rrlyrae.  I get the same error as I did without specifying the url.  

Any suggestions welcome.  Thanks.

(base) ☁  SPLUS-d270  python test_gats.py
Traceback (most recent call last):
  File "test_gats.py", line 3, in <module>
    rrlyrae = datasets.fetch_rrlyrae(url="https://github.com/astroML/astroML-data/raw/master/datasets/RRLyr_ugriz_templates.tar.gz")
  File "/Users/kanaan/anaconda3/lib/python3.7/site-packages/gatspy/datasets/rrlyrae.py", line 389, in fetch_rrlyrae
    cache_kwargs=kwargs)
  File "/Users/kanaan/anaconda3/lib/python3.7/site-packages/gatspy/datasets/rrlyrae.py", line 91, in __init__
    self._load_data()
  File "/Users/kanaan/anaconda3/lib/python3.7/site-packages/gatspy/datasets/rrlyrae.py", line 95, in _load_data
    **(self.cache_kwargs or {}))
  File "/Users/kanaan/anaconda3/lib/python3.7/site-packages/gatspy/datasets/rrlyrae.py", line 45, in _get_download_or_cache
    fhandle = urlopen(src_url)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/kanaan/anaconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
